services:
  api:
    image: ghcr.io/zemcikerik/schema-lens/api:master
    restart: on-failure:3
    depends_on:
      db:
        condition: service_healthy
      formatter:
        condition: service_started
    volumes:
      - ${STORAGE_PROFILE_PICTURE_FOLDER_PATH}:/app/profile-pictures
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@db:1521/FREEPDB1
      - spring.datasource.username=${DB_APP_USER}
      - spring.datasource.password=${DB_APP_PASSWORD}
      - storage.profile-picture.folder-path=/app/profile-pictures
      - project.password-encryption-key=${PROJECT_PASSWORD_ENCRYPTION_KEY}
      - jwt.signing-key=${JWT_SIGNING_KEY}
      - oracle.format.api-base-url=http://formatter:8000
    networks:
      - db
      - formatter
      - reverse-proxy
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1536M

  ui:
    image: ghcr.io/zemcikerik/schema-lens/ui:master
    restart: on-failure:3
    networks:
      - reverse-proxy
    volumes:
      - ${STORAGE_PROFILE_PICTURE_FOLDER_PATH}:/usr/share/nginx/html/static/profile-pictures
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  formatter:
    image: ghcr.io/zemcikerik/schema-lens/formatter:master
    restart: on-failure:3
    networks:
      - formatter
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  reverse-proxy:
    image: ghcr.io/zemcikerik/schema-lens/reverse-proxy:master
    restart: on-failure:3
    depends_on:
      - api
      - ui
    ports:
      - '80:8080'
    networks:
      - reverse-proxy
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  db:
    image: gvenzl/oracle-free:slim
    restart: on-failure:3
    volumes:
      - ${DB_DATA_FOLDER_PATH}:/opt/oracle/oradata
    environment:
      ORACLE_PASSWORD: ${DB_ROOT_PASSWORD}
      APP_USER: ${DB_APP_USER}
      APP_USER_PASSWORD: ${DB_APP_PASSWORD}
    networks:
      - db
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    healthcheck:
      test: [ "CMD", "healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      start_interval: 5s

networks:
  db:
  formatter:
  reverse-proxy:
