on:
  push:
    branches: [ master ]

name: CI/CD

jobs:
  ui-build-and-test:
    name: '[UI] Build and test'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./ui

      - name: Build
        run: npm run build
        working-directory: ./ui

      - name: Lint
        run: npm run lint
        working-directory: ./ui

      - name: Test
        run: npm run test
        working-directory: ./ui

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui-dist
          path: ./ui/dist
          if-no-files-found: error
          retention-days: 30

  ui-build-tocker:
    name: '[UI] Build Docker'
    runs-on: ubuntu-latest
    needs: [ ui-build-and-test ]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ui-dist
          path: ./ui/dist

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/zemcikerik/schema-lens/ui

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./ui
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
